language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
- '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_f1f7ae471c0b_key -iv $encrypted_f1f7ae471c0b_iv -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d'
after_success:
- codecov
- '[ -f ~/.dropbox_uploader ] && ./dropbox_uploader.sh upload build/libs/TicTacToe.jar travis-artifacts/$TRAVIS_JOB_NUMBER/'
